imports:
    - { resource: day_services.yml }

services:
    jgi.swedish_dates.datemanager:
        class: JGI\SwedishDates\Manager\DateManager
        arguments:
            - @jgi.swedish_dates.day.chain