imports:
    - { resource: day_services.yml }

services:
    JGI\SwedishDates\Manager\DateManager:
        class: JGI\SwedishDates\Manager\DateManager
        arguments:
            - '@JGI\SwedishDates\Date\DayChain'

    jgi.swedish_dates.datemanager:
        alias: JGI\SwedishDates\Manager\DateManager

    JGI\SwedishDatesBundle\Twig\TwigExtensions:
        class: JGI\SwedishDatesBundle\Twig\TwigExtensions
        arguments:
            - '@JGI\SwedishDates\Manager\DateManager'
        tags:
            - { name: twig.extension }
