imports:
    - { resource: red_day_services.yml }
    - { resource: name_services.yml }

services:
    jgi.swedish_dates.datemanager:
        class: JGI\SwedishDates\Manager\DateManager
        arguments:
            - @jgi.swedish_dates.red_day.chain
            - @jgi.swedish_dates.name.chain
